export const countryCodes = [
  { code: "+91", country: "IN", label: "India (+91)" },
  { code: "+1", country: "US", label: "US/CA (+1)" },
  { code: "+44", country: "GB", label: "UK (+44)" },
  { code: "+61", country: "AU", label: "Australia (+61)" },
  { code: "+49", country: "DE", label: "Germany (+49)" },
  { code: "+33", country: "FR", label: "France (+33)" },
  { code: "+81", country: "JP", label: "Japan (+81)" },
  { code: "+86", country: "CN", label: "China (+86)" },
  { code: "+971", country: "AE", label: "UAE (+971)" },
  { code: "+966", country: "SA", label: "Saudi (+966)" },
  { code: "+65", country: "SG", label: "Singapore (+65)" },
  { code: "+60", country: "MY", label: "Malaysia (+60)" },
  { code: "+82", country: "KR", label: "S. Korea (+82)" },
  { code: "+39", country: "IT", label: "Italy (+39)" },
  { code: "+34", country: "ES", label: "Spain (+34)" },
  { code: "+31", country: "NL", label: "Netherlands (+31)" },
  { code: "+46", country: "SE", label: "Sweden (+46)" },
  { code: "+41", country: "CH", label: "Switzerland (+41)" },
  { code: "+55", country: "BR", label: "Brazil (+55)" },
  { code: "+52", country: "MX", label: "Mexico (+52)" },
  { code: "+27", country: "ZA", label: "S. Africa (+27)" },
  { code: "+234", country: "NG", label: "Nigeria (+234)" },
  { code: "+254", country: "KE", label: "Kenya (+254)" },
  { code: "+62", country: "ID", label: "Indonesia (+62)" },
  { code: "+63", country: "PH", label: "Philippines (+63)" },
  { code: "+92", country: "PK", label: "Pakistan (+92)" },
  { code: "+880", country: "BD", label: "Bangladesh (+880)" },
  { code: "+94", country: "LK", label: "Sri Lanka (+94)" },
  { code: "+977", country: "NP", label: "Nepal (+977)" },
  { code: "+7", country: "RU", label: "Russia (+7)" },
  { code: "+48", country: "PL", label: "Poland (+48)" },
  { code: "+353", country: "IE", label: "Ireland (+353)" },
  { code: "+64", country: "NZ", label: "New Zealand (+64)" },
  { code: "+47", country: "NO", label: "Norway (+47)" },
  { code: "+45", country: "DK", label: "Denmark (+45)" },
  { code: "+358", country: "FI", label: "Finland (+358)" },
  { code: "+972", country: "IL", label: "Israel (+972)" },
  { code: "+90", country: "TR", label: "Turkey (+90)" },
  { code: "+20", country: "EG", label: "Egypt (+20)" },
  { code: "+974", country: "QA", label: "Qatar (+974)" },
  { code: "+968", country: "OM", label: "Oman (+968)" },
  { code: "+973", country: "BH", label: "Bahrain (+973)" },
  { code: "+965", country: "KW", label: "Kuwait (+965)" },
];
